branches:
    only:
    - master
script: 
    - ./curl-travis.sh
after_success:
    - git commit -m `date -I`
    - git push "https://sirius1242:${GH_TOKEN}@github.com/sirius1242/bing-wallpaper-collect.git" master
